version: 2.1
workflows:
  build-test:
    jobs:
      - build
      - check-black
      - mypy
      - pytest

jobs:
  build:
    docker:
      - image: circleci/python:3.9.0
    environment:
      # only build for CPython 3.x
      CIBW_BUILD: cp3*-*
      CIBW_BEFORE_ALL_LINUX: "yum install -y jack-audio-connection-kit-devel libsndfile swig"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            pip install --user cibuildwheel==1.11.0
            cibuildwheel --output-dir wheelhouse
      - store_artifacts:
          path: wheelhouse/

  mypy:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get -y install libjack-jackd2-dev libsndfile1 swig
            pip install -e .
            pip install mypy
            mypy amio/

  check-black:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          command: |
            pip install black
            black --check .

  pytest:
    docker:
      - image: circleci/python:3.9.0
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get -y install libjack-jackd2-dev libsndfile1 swig
            pip install -e .
            pip install pytest
            pytest
